#!/bin/bash

# This script takes a list of sample IDs and copies the snapr-generated .bam files to a specified S3 bucket

######## Specify inputs #######################################################

# SAMPLELIST="samples.txt"
# BUCKET="s3://mayo-u01-rnaseq/"
# TARGETDIR="s3://u01-amp-ad/SNAPR-output/Rush-Broad-sample-swap/"

# usage
# ./copy_bam_files samples.txt s3://mayo-u01-rnaseq/ \
#                s3://u01-amp-ad/SNAPR-output/Rush-Broad-sample-swap

SAMPLELIST=$1
BUCKET=$2
TARGETDIR=$3

# Get full list of all *.snap.bam files from S3 bucket
FILE_LIST=`mktemp s3-bucket-contents.XXXXXXXX`
aws s3 ls ${BUCKET} --recursive \
    | grep -e ".snap\.bam$" \
    | awk '{print $4}' \
    > $FILE_LIST ;

# add location for keeping track of what's copied
COPIEDFILES=`mktemp s3-target-contents.XXXXXXXX`

# find .bam file corresponding to each sample in SAMPLELIST, copy if not already copied (TODO: warn if more than 1)
while read -r line
do
    SOURCEFILE=`grep ${line} ${FILE_LIST}`
    echo ${BUCKET}${SOURCEFILE} ${TARGETDIR}
    # Get list of files in target S3 bucket  
    aws s3 ls ${TARGETDIR} --recursive \
        | awk '{print $4}' \
        > $COPIEDFILES ;
    if [[ ! -n `grep ${line} ${COPIEDFILES}` ]]
      then
        aws s3 cp ${BUCKET}${SOURCEFILE} ${TARGETDIR} --dryrun
    fi
done < ${SAMPLELIST}

